### ISSUE TITLE
Saving a point cloud as E57 incorrectly saves the pose transformed cartesianBounds 

### ISSUE THREAD

**Issue by fahadm** [CloudCompare/CloudCompare#1027]
**Describe the bug**
Cloud compare always saves the pose transformed coordinates for the cartesian bounds when exporting a pointcloud to the e57 format.

As can be seen here:
https://github.com/CloudCompare/CloudCompare/blob/a8dbddebf29e2cd4ebf132b8a38a7d4101304d23/plugins/core/IO/qE57IO/src/E57Filter.cpp#L201-L225

According to the E57 spec, the cartesian bounding box should be in the local coordinate system.
While saving cloud compare `transforms` the `cartesianbounds` which makes the bounding box coordinates in file-level coordinate system while the points are in the local coordinate system.

This causes cloud compare to create e57 files which are not compliant to the spec. And might be unusable in 3rd party applications.

**How to reproduce**
- Open a ptx file with a transform
- Save it as e57
- Open the e57 file (do not do the global shift ), see that the e57 file has `cartesianBounds` which are transformed.
**Expected behaviour**
According to the spec the bounds should be in the local coordinate system, and applying the pose causes it to be in file-level coordinates.

**Your environment**
 - CC Version 2.10.2
 - OS & Version: Mac OS Mojave
 - Graphics card: Intel Iris 6100

**Comment by dgirardeau** [comment]
Good catch!

**Comment by dgirardeau** [comment]
And commit ad5378186897be807eda16bfd51cf36720cd457e should fix this. Thanks for the feedback!

**Comment by sdgoldstein** [comment]
I'm still seeing this issue in v2.12.4.  Steps that reproduced it for me:

1.  Open E57 File in Cloud Compare
2.  Use Tools -> Level
3.  Save as new E57 file

My resulting file has:

bounding Z coordinate range -10.04 to -0.15 
Z coordinate points shifted by the negative of the z-pose -(-7) = +7

**Comment by dgirardeau** [comment]
Oopsy. And it's still there for a long time!

I've hopefully fixed it: 51568ae4b1e2522df48fa60b061ba7b2897a2cb5

You can test that with the latest 2.13.beta version (for Windows).

**Comment by dgirardeau** [comment]
@sdgoldstein Make sure to use the latest 2.13 beta version (10th of Feb) as there was a big bug with the E57 file export introduced in the commit above (on the 27th of January).
