### ISSUE TITLE
pv files not loaded in 2.11.1

### ISSUE THREAD

**Issue by MEpping** [CloudCompare/CloudCompare#1307]
When I try to open .pv files which opened fine in version 2.9.1 I get following errors:
[I/O] CC has caught an exception while loading file '<pathotofile>60400000.pv'
[I/O] Exception: invalid vector<T> subscript
An error occurred while loading '60400000': see console

**How to reproduce**
Create a pv-file (e.g. in some other tool), try to open it with CC.

**Expected behaviour**
pv-files should load without errors.

**Additional context**
pv files are simple arrays of float values (x,y, z, scalar), see e.g. KITTI dataset.

**Your environment**
CC Version 2.11.1, Win 10 64bit, Nvidia Quadro M1200

**Comment by WargodHernandez** [comment]
I was able to confirm the bug, I'll have a PR to fix the issue later today.

**Comment by WargodHernandez** [comment]
Sorry about the long delay, I got busy with other projects/life.
@dgirardeau  supplied the fix in #1314

**Comment by dgirardeau** [comment]
And here is a preview version of the 2.11.2 version of CC that should fix the issue:
https://www.cloudcompare.org/release/CloudCompare_v2.11.2.preview_setup_x64.exe

**Comment by MEpping** [comment]
Unfortunately the preview setup does not seem to fix the issue for me. I still get the same error.

**Comment by WargodHernandez** [comment]
Yes, sorry should have said it is in the v2.11.2 version to be released soon, I believe there is a preview of it on the forum currently

**Comment by dgirardeau** [comment]
I must have mixed things up. I updated the preview version (you can use the same link as above).

**Comment by MEpping** [comment]
Ok, found it, and it works. Thanks for your efforts, @WargodHernandez @dgirardeau !
